import streamlit as st
import pandas as pd
import joblib

model = joblib.load('InsuranceLearning2.pkl')

import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt

# --- Load Model ---
model = joblib.load('InsuranceLearning.pkl')

# --- Page Config ---
st.set_page_config(page_title="Insurance Charges Predictor", layout="wide")

# --- Header ---
st.title("Insurance Charges Predictor")
st.markdown("Predict your insurance charges based on personal information.")

st.markdown("---")

# --- User Inputs in Columns ---
st.header("Enter Your Information")
col1, col2 = st.columns(2)

with col1:
    age = st.slider("Age", 0, 120, 30)
    sex = st.selectbox("Sex", ["female", "male"])
    bmi = st.slider("BMI", 0.0, 60.0, 25.0)

with col2:
    children = st.selectbox("Children", ["no", "yes"])
    smoker = st.selectbox("Smoker", ["no", "yes"])
    region = st.selectbox("Region", ["northeast", "northwest", "southeast", "southwest"])

# --- Map categorical inputs to numeric ---
sex_map = {"female": 0, "male": 1}
children_map = {"no": 0, "yes": 1}
smoker_map = {"no": 0, "yes": 1}
region_map = {"northeast": 0, "northwest": 1, "southeast": 2, "southwest": 3}

sex = sex_map[sex]
children = children_map[children]
smoker = smoker_map[smoker]
region = region_map[region]

# --- Predict Button ---
if st.button("Predict Charges"):
    input_data = pd.DataFrame([[age, sex, bmi, children, smoker, region]],
                              columns=['age', 'sex', 'bmi', 'children', 'smoker', 'region'])
    
    prediction = model.predict(input_data)[0]
    
    # Display Result
    st.metric(label="Predicted Insurance Charges", value=f"${prediction:,.2f}")
    
    # Disclaimer
    st.markdown("---")
    st.subheader("Disclaimer")
    st.markdown("""
    **Important:** This prediction is generated by a machine learning model and is **not 100% accurate**.  
    It should be used for **informational purposes only** and does not constitute professional financial or insurance advice.  
    Actual insurance charges may vary based on additional factors not captured by this model.
    """)

